/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_game_isoball_util_NativePhysicsUtil */

#ifndef _Included_com_game_isoball_util_NativePhysicsUtil
#define _Included_com_game_isoball_util_NativePhysicsUtil
#ifdef __cplusplus


extern "C" {
#endif
/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    InitializeWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_game_isoball_util_NativePhysicsUtil_InitializeWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    UpdateWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_game_isoball_util_NativePhysicsUtil_UpdateWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    AddBall
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_game_isoball_util_NativePhysicsUtil_AddBall
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    SetBallVelocity
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_com_game_isoball_util_NativePhysicsUtil_SetBallVelocity
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    GetBallPosition
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_game_isoball_util_NativePhysicsUtil_GetBallPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    GetBallPositions
 * Signature: ()Lcom/game/isoball/util/BallPositionHolder;
 */
JNIEXPORT jobject JNICALL Java_com_game_isoball_util_NativePhysicsUtil_GetBallPositions
  (JNIEnv *, jclass);

/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    AddEdge
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_game_isoball_util_NativePhysicsUtil_AddEdge
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    AddCircularLauncher
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_game_isoball_util_NativePhysicsUtil_AddCircularLauncher
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_game_isoball_util_NativePhysicsUtil
 * Method:    DepthSortGameObjects
 * Signature: ([Lcom/game/isoball/gameObjects/GameObject;)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_game_isoball_util_NativePhysicsUtil_DepthSortGameObjects
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
